### ISSUE TITLE
Make action work cross platform

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/puppeteer-screenshot-action#3]
Currently, the action uses a linux filepath for the chrome executable, which restricts it to being only usable on Ubuntu. It would be useful to set the `executablePath` for Puppeteer dependent on the OS. You'll have to find the locations of the chrome executable on MacOS and Windows but otherwise then you can set it fairly simply.

I am fine if you use static strings for each of the OS or use a tool like `which`. To figure out which OS you are running, the `runner` context should have the string. One can examine what is inside a context by running the following example in a workflow: [Example printing context information to the log file](https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#example-printing-context-information-to-the-log-file)

**Comment by muhameddelic** [comment]
Hi @lannonbr I am happy to take this

**Comment by muhameddelic** [comment]
One note, I checked the installed software on the MacOS images and Chrome is not listed. Also, we can't use Safari to run puppeteer as it's only compatible with Chrome. https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#macos-1014

**Comment by lannonbr** [comment]
Alright yeah it seems that is the case, but I'm still up for also supporting Windows. Just assigned you to the issue.
